#+title: Diamonds
#+date: 2022-06-30
#+draft: false
#+filetags: minecraft

The adventures of Sir Rusll & Jorge(Horr-Hay)

It was a sunny day, Me along with Sir Xeon and Sir Wolfsteindromon(Wolfie) had recently set up our base near a bluish green floating island. Sir Wolfie took charge of handling the crops while I was on the berry farm. Now berries are quite a good food source in the initial stage because they harvest twice a day. I learnt this on my adventure with Sir Jun.

And one by one I set up 7 rows of berry farms. Sir Wolfie mentioned he could see the whole thing on his map. Standing over the so-called "base" with a crafting table and a couple of storage chests and no walls, all you could see was shades of red. Red spanning from the dusty ground to the snowy white on the left, greeny grass on the right and the browny spruce up ahead.

I would name it as The Red Garden and it would feed us in these treacherous hours one hunger at a time. 

Sir Xeon raised a voice that berries would be inefficient for hunger and he would rather hunt than survive on little berries(Although he is vegan in the connected parallel universe). We all agreed in unison.

While Sir Wolfie's parallel himself was not connected to the grid, Me and Sir Xeon cleared out the trees for our base. We even came up with a system for pointing out things. We called it "Ping". If someone pings a block, it would appear highlighted to the others.  

I looked up at the floating island and I promised myself I would reach up there today, no matter what. 
Me and Sir Xeon decided it was time to go on a mining expedition. I grabbed the tools and food for our underground journey. We staircased down into the underground while lighting up. Sir Xeon fell into a cave and voiced for help. I carefully staircased down. The ground was wet, air thick and darkness all around. We lit up the cave with torches following the agreed convention of placing those on right wall so we could backtrack on surface if we were lost or worse, being chased. Sir Xeon stepped on something hard and shiny. Upon closer inspection with our detector "Jade" we found out these were precious metals. Some could be mined with stone pickaxe while the precious ones required iron pickaxe. Fortunately Sir Xeon had an iron pickaxe on him. We grabbed what we could and headed back to the surface, slept through the night and headed down the first thing in the morning. Step 1 was to light up the whole cave so we knew our way around. During the lighting up we came across an opening to another cave and when we entered and my Notch we couldn't believe our eyes. Standing at the entrance there was a waterfall near us and a lavafall up ahead. The cave was so high we could never reach the ceiling and the chasm so deep we would never want to. We gathered up some courage and lit up the area while clearing out the monsters together. 

After the area was lit, we ventured down into the chasm with the waterfall. More monsters, more lighting. We faced monsters we couldn't dream in our worst nightmares. Witches who threw poisonous potions at you and Slimes who multiplied into smaller slimes upon its death. They kept coming and we held our ground. After a bloodshed battle, we emerged victorious. We were quite familiar with the encounters of the monsters of the night. We patched ourselves up and marched ahead into the darkness.
Upon checking our position we were almost close to the bedrock, the lowest position in the world. We were determined to find diamonds and we were not going to give up this easy.  
This was no easy task and I, being the trusty engineer, pulled out the big guns, Vein Mining. Vein mining allows you to mine similar blocks in one go. The catch, it uses up the durability so the more blocks you mine the quicker your tools break. I placed my crafting table and filled my whole inventory with stone pickaxe. We were mining like a drilling machine. During our mining expedition we found 26 diamonds and headed back home as fast as we could. 

Sir Xeon made some food while I went on my daily stroll. I saw the floating island, rushed back to base, grabbed some stone blocks and ran to the floating island. I towered one by one and reached the top. There were some glowing trees and glowing water. I swam in the water and came down. I told Sir Xeon about this and he said it was a slime island. We had our dinner and called it a day.  

It was a good day.  

